# Generated by Django 4.2.11 on 2024-05-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(choices=[('lecture', 'Wykład'), ('lab', 'Laboratorium'), ('sport', 'Sala sportowa')], max_length=10)),
            ],
        ),
    ]
