# Generated by Django 5.1.3 on 2024-11-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('institutions', '0003_institution_logo'),
        ('room_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('equipment', models.ManyToManyField(blank=True, help_text='Wybierz sprzęt dostępny w sali', to='equipment.equipment')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='institutions.institution')),
                ('room_types', models.ManyToManyField(blank=True, help_text='Wybierz typy, do których sala się nadaje', to='room_types.roomtype')),
            ],
        ),
    ]
