# Generated by Django 4.2.11 on 2024-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Wykład'), ('lab', 'Laboratorium'), ('seminar', 'Seminarium'), ('project', 'Projekt'), ('exercises', 'Ćwiczenia'), ('sport', 'Ćwiczenia sportowe')], max_length=10),
        ),
    ]
