# Generated by Django 4.2.11 on 2024-05-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('lecture', 'Wykład'), ('lab', 'Laboratorium'), ('seminar', 'Seminarium'), ('project', 'Projekt'), ('exercises', 'Ćwiczenia'), ('sport', 'Ćwiczenia sportowe')], max_length=20, null=True),
        ),
    ]
