# Generated by Django 4.2.11 on 2024-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Wykład'), ('lab', 'Laboratorium'), ('seminar', 'Seminarium'), ('project', 'Projekt'), ('exercises', 'Ćwiczenia'), ('sport', 'Ćwiczenia sportowe')], default='lecture', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='Wybierz sprzęt dostępny w sali', to='rooms.equipment'),
        ),
    ]
