# Generated by Django 4.2.11 on 2024-05-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_roomtype_remove_room_room_type_room_room_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_types',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('lecture', 'Wykład'), ('lab', 'Laboratorium'), ('seminar', 'Seminarium'), ('project', 'Projekt'), ('exercises', 'Ćwiczenia'), ('sport', 'Ćwiczenia sportowe')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
