# Generated by Django 4.2.11 on 2024-05-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_room_room_types_room_room_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lecture', 'Wykład'), ('lab', 'Laboratorium'), ('seminar', 'Seminarium'), ('project', 'Projekt'), ('exercises', 'Ćwiczenia'), ('sport', 'Ćwiczenia sportowe')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='room_types',
            field=models.ManyToManyField(blank=True, help_text='Wybierz typy, do których sala się nadaje', to='rooms.roomtype'),
        ),
    ]
