# Generated by Django 5.1.3 on 2024-11-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('institutions', '0003_institution_logo'),
        ('room_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_type', models.ForeignKey(blank=True, help_text='Opcjonalny typ zajęć', null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_types.roomtype')),
                ('equipment', models.ManyToManyField(blank=True, help_text='Wybierz wymagane wyposażenie dla zajęć', to='equipment.equipment')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutions.institution')),
            ],
        ),
    ]
