# Generated by Django 5.1.3 on 2024-11-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('room_types', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.AddField(
            model_name='course',
            name='room_types',
            field=models.ManyToManyField(blank=True, help_text='Wybierz typy zajęć', to='room_types.roomtype'),
        ),
    ]
