# Generated by Django 4.2.11 on 2024-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('lecture', 'Wykład'), ('lab', 'Laboratorium'), ('seminar', 'Seminarium'), ('project', 'Projekt'), ('exercises', 'Ćwiczenia'), ('sport', 'Ćwiczenia sportowe')], default='lecture', max_length=50, null=True),
        ),
    ]
