# Generated by Django 4.2.11 on 2024-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='size',
            field=models.IntegerField(default=20, help_text='Liczba osób w grupie'),
        ),
    ]
