# Generated by Django 4.2.11 on 2024-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.CharField(blank=True, help_text='Wydział lub specjalizacja grupy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('1', 'Klasa 1'), ('2', 'Klasa 2'), ('3', 'Klasa 3'), ('4', 'Klasa 4'), ('5', 'Klasa 5'), ('6', 'Klasa 6'), ('7', 'Klasa 7'), ('8', 'Klasa 8'), ('S1', 'Semestr 1'), ('S2', 'Semestr 2'), ('S3', 'Semestr 3'), ('S4', 'Semestr 4'), ('S5', 'Semestr 5'), ('S6', 'Semestr 6'), ('S7', 'Semestr 7'), ('S8', 'Semestr 8'), ('S9', 'Semestr 9'), ('S10', 'Semestr 10'), ('S11', 'Semestr 11'), ('S12', 'Semestr 12')], default='1', help_text='Klasa lub semestr, do którego grupa należy', max_length=3),
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.CharField(blank=True, help_text='Kierunek, jeśli dotyczy', max_length=100, null=True),
        ),
    ]
