# Generated by Django 4.2.11 on 2024-05-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('group', '0003_group_faculty_group_level_alter_group_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='institutions.institution'),
        ),
    ]
