# Generated by Django 4.2.11 on 2024-05-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('group', '0004_group_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='department.department'),
        ),
    ]
