# Generated by Django 5.1.3 on 2024-11-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('institutions', '0003_institution_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('title', models.CharField(choices=[('inż.', 'inż.'), ('mgr inż.', 'mgr inż.'), ('dr inż.', 'dr inż.'), ('dr hab. inż.', 'dr hab. inż.'), ('prof. dr hab. inż.', 'prof. dr hab. inż.')], default='mgr inż.', max_length=50)),
                ('courses', models.ManyToManyField(blank=True, help_text='Kursy, które nauczyciel może prowadzić', to='course.course')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='institutions.institution')),
            ],
        ),
    ]
