# Generated by Django 4.2.11 on 2024-05-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('inż.', 'inż.'), ('mgr inż.', 'mgr inż.'), ('dr inż.', 'dr inż.'), ('dr hab. inż.', 'dr hab. inż.'), ('prof. dr hab. inż.', 'prof. dr hab. inż.')], default='mgr inż.', max_length=50),
        ),
    ]
