# Generated by Django 4.2.11 on 2024-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_type'),
        ('teachers', '0002_teacher_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Kursy, które nauczyciel może prowadzić', to='course.course'),
        ),
    ]
