# Generated by Django 5.1.3 on 2024-11-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_remove_course_course_type_course_room_types'),
        ('group', '0007_alter_group_department'),
        ('institutions', '0003_institution_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'unique_together': {('institution', 'group', 'course')},
            },
        ),
    ]
