# Generated by Django 5.1.3 on 2024-11-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectFrequency', '0001_initial'),
        ('course', '0002_remove_course_course_type_course_room_types'),
        ('department', '0003_alter_department_faculty'),
        ('group', '0007_alter_group_department'),
        ('institutions', '0003_institution_logo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectfrequency',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectfrequency',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AlterField(
            model_name='subjectfrequency',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectfrequency',
            unique_together={('institution', 'group', 'department', 'course')},
        ),
    ]
