# Generated by Django 5.1.3 on 2024-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectFrequency', '0002_alter_subjectfrequency_unique_together_and_more'),
        ('group', '0007_alter_group_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfrequency',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_subjects', to='group.group'),
        ),
    ]
