# Generated by Django 5.1.3 on 2024-11-15 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeConfiguration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeconfiguration',
            name='break_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=900), help_text='Długość przerw, jeśli są jednakowe.', null=True),
        ),
        migrations.AlterField(
            model_name='timeconfiguration',
            name='custom_breaks',
            field=models.JSONField(blank=True, help_text="Długości przerw dla każdej lekcji w formacie JSON. Przykład: {1: '00:15:00', 2: '00:10:00'}", null=True),
        ),
        migrations.AlterField(
            model_name='timeconfiguration',
            name='lesson_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=2700), help_text='Czas trwania pojedynczej lekcji (np. 45 minut).'),
        ),
    ]
