# Generated by Django 5.1.3 on 2024-11-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeConfiguration', '0002_alter_timeconfiguration_break_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeconfiguration',
            name='end_time',
            field=models.TimeField(default='20:00', help_text='Czas zakończenia ostatnich zajęć.'),
        ),
    ]
