# Generated by Django 4.2.11 on 2024-05-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('primary', 'Szkoła Podstawowa'), ('secondary', 'Szkoła Średnia'), ('higher', 'Szkoła Wyższa')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
