# Generated by Django 5.1.3 on 2024-11-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logos/'),
        ),
    ]
