# Generated by Django 5.1.3 on 2024-11-07 19:25

import django.db.models.deletion
import schedules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('group', '0007_alter_group_department'),
        ('institutions', '0003_institution_logo'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_type', models.CharField(choices=[('weekly', 'Co tydzień'), ('even', 'Tygodnie parzyste'), ('odd', 'Tygodnie nieparzyste')], default='weekly', max_length=10)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
                ('start_time', models.TimeField(default='14:00')),
                ('end_time', models.TimeField(default='15:30')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('group', models.ForeignKey(default=schedules.models.get_default_group, on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='institutions.institution')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
