# Generated by Django 4.2.11 on 2024-05-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_remove_schedule_time_slot_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='week_type',
            field=models.CharField(choices=[('weekly', 'Co tydzień'), ('even', 'Tygodnie parzyste'), ('odd', 'Tygodnie nieparzyste')], default='weekly', max_length=10),
        ),
    ]
