# Generated by Django 5.1.3 on 2024-11-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_group_department'),
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='group',
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ManyToManyField(to='group.group'),
        ),
    ]
