# Generated by Django 5.1.3 on 2024-11-20 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_faculty'),
        ('institutions', '0003_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.institution'),
        ),
    ]
